services:
  - type: web
    name: prompt-glory-ui
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://prompt-glory.onrender.com/
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false